#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'fileutils'
require 'shellwords'

require 'colorize'

MPV = '/Applications/mpv.app/Contents/MacOS/mpv --really-quiet'

mpv_options = ''
all_videos = true
counter = 0

ARGV.each do |opt|
  case opt.downcase
  when 'f', 'fs', 'full'
    mpv_options = '--fs'
  when /^\d+$/
    all_videos = false
    counter = opt.to_i
  end
end

def find(vid, videos)
  x = videos.select { |x| x.include?(vid) }

  if x.size == 1
    x.first
  else
    nil
  end
end

unless File.exist?('metadata.csv')
  puts '==> There is no metadata.csv file'
  exit 1
end

##
# This will be a list of all the downloaded videos that
# have not yet been placed in the videos directory
##
vidoes = Dir['*.mp4'].map { |v| v }

x = []

CSV.read('metadata.csv', headers: true).each do |row|
  f = find(row['videoId'], vidoes)
  next if f.nil?

  x << { filename: f, duration: row['duration'], datePublished: row['datePublished'] }
end

unless x.any?
  puts '    Nothing found'.red
  exit 1
end

x.sort! { |a, b| a[:datePublished] <=> b[:datePublished] }

i = 0
x.each do |y|
  i += 1
  puts "[#{i}] #{y[:filename]} #{y[:datePublished]} #{y[:duration]}".green

  r = system("#{MPV} #{mpv_options} #{Shellwords.escape(y[:filename])}")

  if r
    puts "    #{y[:filename]} moved to videos".green
    FileUtils.move(y[:filename], 'videos/')
  else
    puts "    Somthing happened, leaving #{y[:filename]} in place".bold
  end

  next if all_videos
  break if i == counter
end
