#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'fileutils'
require 'shellwords'

require 'colorize'

MPV = '/Applications/mpv.app/Contents/MacOS/mpv --really-quiet'

MPV_OPTIONS = ARGV.join(' ')

def find(vid, videos)
  x = videos.select { |x| x.include?(vid) }

  if x.size == 1
    x.first
  else
    nil
  end
end

unless File.exist?('metadata.csv')
  puts '==> There is no metadata.csv file'
  exit 1
end

##
# This will be a list of all the downloaded videos that
# have not yet been placed in the videos directory
##
vidoes = Dir['*.mp4'].map { |v| v }

x = []

CSV.read('metadata.csv', headers: true).each do |row|
  f = find(row['videoId'], vidoes)
  next if f.nil?

  x << { filename: f, duration: row['duration'], datePublished: row['datePublished'] }
end

unless x.any?
  puts '    Nothing found'.red
  exit 1
end

x.sort! { |a, b| a[:datePublished] <=> b[:datePublished] }

x.each do |y|
  puts "==> #{y[:filename]} #{y[:datePublished]} #{y[:duration]}".green

  r = system("#{MPV} #{MPV_OPTIONS} #{Shellwords.escape(y[:filename])}")

  if r
    puts "    #{y[:filename]} moved to videos".green
    FileUtils.move(y[:filename], 'videos/')
  else
    puts "    Somthing happened, leaving #{y[:filename]} in place".bold
  end
end
