#!/usr/bin/env ruby
# frozen_string_literal: true

K = 1024
M = 1024 * 1024
G = 1024 * 1024 * 1024

args = ARGV.dup

full = args.delete('-v')
script = args.delete('-s')

def hsize(bytes, zero = false)
  return '-' if bytes == 0 && zero == false

  if bytes >= G
    '%.2fGb' % (bytes.to_f / G)
  elsif bytes >= M
    '%.2fMb' % (bytes.to_f / M)
  elsif bytes >= K
    '%.2fKb' % (bytes.to_f / K)
  else
    "#{bytes}b"
  end
end

def as_list(path, filename)
  return [] unless File.exist?("#{path}/#{filename}")

  File.open("#{path}/#{filename}", 'r').read.split("\n").map { |x| x.split(/\s+/).first }
end

def outstanding(path, txts)
  return 0 if txts.size > 2

  txts.delete('downloaded.txt')

  done = as_list(path, 'downloaded.txt')

  todo = 0
  as_list(path, txts.first).each do |vid|
    next if done.include?(vid)
    todo += 1
  end

  return todo
end

def review(path)
  mp4_count = 0
  mp4_size  = 0

  part_count = 0
  part_size  = 0

  txts = []

  Dir["#{path}/*"].each do |filename|
    if filename.end_with?('.mp4')
      mp4_count += 1
      mp4_size  += File.size(filename)
    elsif filename.end_with?('.part')
      part_count += 1
      part_size  += File.size(filename)
    elsif filename.end_with?('.txt')
      txts << File.basename(filename)
    end
  end

  to_download = outstanding(path, txts)

  [to_download, mp4_count, mp4_size, part_count, part_size]
end

def merge(a, b)
  c = []
  a.each_with_index do |e, i|
    if b[i] == '-'
      c << e
    else
      c << e + b[i]
    end
  end
  c
end

data = []

t = [0,0,0,0,0]

Dir['*'].sort.each do |dir|
  next unless File.directory?(dir)

  to_download, mp4_count, mp4_size, part_count, part_size = review(dir)

  next if full.nil? && to_download == 0 && mp4_count == 0 && part_count == 0

  to_download = to_download.zero? ? '-' : to_download
  mp4_count = mp4_count.zero? ? '-' : mp4_count
  part_count = part_count.zero? ? '-' : part_count

  t = merge(t, [to_download, mp4_count, mp4_size, part_count, part_size])

  data << [dir, to_download, mp4_count, hsize(mp4_size), part_count, hsize(part_size)]
end

if script
  header = true
  data.each do |line|
    next if line[2] == '-' || line[2].zero?

    if header
      puts 'process() {'
      puts 'cd $1'
      puts 'mv *.mp4 videos/'
      puts 'cd ..'
      puts '}'
      header = false
    end

    puts "process #{line[0]}"
  end
else
  puts '%-30s │ %10s │ %23s │ %23s │' % ['Name', 'Pending', 'Downloaded', 'Partial']
  puts '───────────────────────────────┼────────────┼────────────┬────────────┼────────────┬────────────┤'

  data << ['TOTAL', t[0], t[1], hsize(t[2]), t[3], hsize(t[4])]

  data.each do |line|
    puts '%-30s │ %10s │ %10s │ %10s │ %10s │ %10s │' % line
  end
end
